### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by zecamigo** [ogarcia/ultrasonic#725]
## Problem description

Trying to connect with my selfhosted airsonic installation, but I get a connection failure, which doesn't appear accessing the subsonic demo server.

Should be noted the exact same settings work with other cliends, such as Subtracks and DSub.
Logs: 

```
12:23:02.366: I SettingsFragment Enabled debug logging to file 
12:23:06.625: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:23:10.317: D NavigationActivity Navigated to org.moire.ultrasonic:id/mediaLibraryFragment 
12:23:31.766: W CommunicationError com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
	at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1695)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:75)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:66)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at org.moire.ultrasonic.service.RESTMusicService.getArtists(RESTMusicService.kt:100)
	at org.moire.ultrasonic.service.CachedMusicService.getArtists(CachedMusicService.kt:127)
	at org.moire.ultrasonic.model.ArtistListModel.load(ArtistListModel.kt:62)
	at org.moire.ultrasonic.model.GenericListModel$loadFromServer$2.invokeSuspend(GenericListModel.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
12:23:37.406: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
12:23:39.104: I ServerSelectorFragment Active server was set to: 1 
12:23:39.109: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:23:42.349: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
12:23:45.190: D NavigationActivity Navigated to org.moire.ultrasonic:id/editServerFragment 
12:23:52.922: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
12:23:52.925: D ActiveServerProvider Cache is invalidated 
12:23:52.926: D ServerSettingsModel$updateItem updateItem updated server setting: ServerSetting(id=1, index=1, name=castle, url=https://castle.noho.st/airsonic, color=null, userName=zeze, password=gestos.imprevistos.verdes.bodes.druidas, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=true, musicFolderId=null, minimumApiVersion=null, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null) 
12:23:52.939: D ActiveServerProvider$getActiveServer getActiveServer retrieved from DataBase, id: 1 cachedServer: ServerSetting(id=1, index=1, name=castle, url=https://castle.noho.st/airsonic, color=null, userName=zeze, password=gestos.imprevistos.verdes.bodes.druidas, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=true, musicFolderId=null, minimumApiVersion=null, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null) 
12:23:56.101: I ServerSelectorFragment Active server was set to: 1 
12:23:56.105: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:23:58.646: D NavigationActivity Navigated to org.moire.ultrasonic:id/artistListFragment 
12:23:58.658: I ActiveServerProvider Switching to new database, id:1 
12:23:58.659: I ActiveServerProvider Switching to new database, id:1 
12:23:59.412: W CommunicationError com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
	at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1695)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:75)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:66)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at org.moire.ultrasonic.service.RESTMusicService.getArtists(RESTMusicService.kt:100)
	at org.moire.ultrasonic.service.CachedMusicService.getArtists(CachedMusicService.kt:127)
	at org.moire.ultrasonic.model.ArtistListModel.load(ArtistListModel.kt:62)
	at org.moire.ultrasonic.model.GenericListModel$loadFromServer$2.invokeSuspend(GenericListModel.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
12:24:02.042: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:37:32.433: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:37:32.459: I Storage StorageFile caches were reset 
12:37:38.216: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
12:37:41.035: I ServerSelectorFragment Active server was set to: 1 
12:37:41.037: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:37:45.148: D NavigationActivity Navigated to org.moire.ultrasonic:id/artistListFragment 
12:37:45.471: W CommunicationError com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
	at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1695)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:75)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:66)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at org.moire.ultrasonic.service.RESTMusicService.getArtists(RESTMusicService.kt:100)
	at org.moire.ultrasonic.service.CachedMusicService.getArtists(CachedMusicService.kt:127)
	at org.moire.ultrasonic.model.ArtistListModel.load(ArtistListModel.kt:62)
	at org.moire.ultrasonic.model.GenericListModel$loadFromServer$2.invokeSuspend(GenericListModel.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 2, column: 4]
12:37:47.884: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
12:37:50.113: D NavigationActivity Navigated to org.moire.ultrasonic:id/settingsFragment 
```

### Steps to reproduce

Fresh Ultrasonic install
Add selfhosted Airsonic server
Get Connection error
Tried both with and without forcing simple password.

### Ultrasonic client

 * **Ultrasonic version**: 3.1.1 F-Droid
 * **Android version**: Android 11 based ROM (DivestOS)
 * **Device info**: OnePlus 5T

### Server

 * **Server name**: Airsonic
 * **Server version**: 10.6.2-RELEASE – May 3, 2020
 * **Protocol used**: https (letsencrypt)

**Comment by ogarcia** [comment]
Is a problem with server that not respect the API:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'madsonic-response' does not match expected ('subsonic-response') for type [simple type, class org.moire.ultrasonic.api.subsonic.response.GetArtistsResponse]
```

**Comment by zecamigo** [comment]
@ogarcia 

Thanks for the quick reply.

This based on the latest opensource version of AirSonic. Have you seen this issue before with this version?
Or do you think it would have something to do with the Yunohost packaging? https://github.com/YunoHost-Apps/airsonic_ynh

**Comment by zecamigo** [comment]
In any case, it does work with other clients, so could you please tag it as an 'enhancement' instead?

**Comment by ogarcia** [comment]
The isse seems caused by this:
https://github.com/YunoHost-Apps/airsonic_ynh/blob/a03966d2b38c3c46b2f561424debe6021a64e9fb/conf/nginx.conf#L24

Is replacing `subsonic` with `madsonic` in responses what causes it not to work.

> In any case, it does work with other clients, so could you please tag it as an 'enhancement' instead?

We will not support servers that do not comply with the API standard.

**Comment by zecamigo** [comment]
If I read it correctly, that actually comes from the source: https://github.com/airsonic/airsonic/issues/260

Please let me know if I'm wrong so I can work with YunoHost people.

**Comment by ogarcia** [comment]
As say in Airsonic repository:
Airsonic isn't maintained anymore, you should migrate to [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced) instead.

**Comment by zecamigo** [comment]
You're probably right, though backwards compatibility would be nice.
Thanks for your time and directions.
