### ISSUE TITLE
Album art doesn't appear in the media notification

### ISSUE THREAD

**Issue by sserenade** [ogarcia/ultrasonic#768]
## Problem description

Album art doesn't appear in the media notification. I can provide more
screenshots or debug logs if needed, but at a glance nothing useful appears.

![Screenshot_20220623-170445](https://user-images.githubusercontent.com/6497404/175436746-2e78a138-11a3-4faa-8d9d-fc374ce29feb.png)

Album art appears in the Now Playing drawer in the app, but not in the notification.

### Steps to reproduce

Play any song and pull down the notification shade.

I've also tested with the demo server to rule out my server, but if it turns out to be transcoding or server related I can change settings.

### Ultrasonic client

 * **Ultrasonic version**: 4.0.0-beta.1
 * **Android version**: 12 (SQ3A.220605.009.B1)
 * **Device info**: Pixel 6 Pro

### Server

 * **Server name**: Airsonic Advanced
 * **Server version**: 11.0.0-SNAPSHOT.20220228185039
 * **Protocol used**: https w/letsencrypt

**Comment by hmueller01** [comment]
What kind of audio files do you use? I see the problem too with m4a files. mp3s work. The cover is shown in Now Playing but not in the notification, lock screen and widget.

**Comment by mradermaxlol** [comment]
I experience something similar with Navidrome, Ultrasonic F-Droid stable. First (downloaded, not cached beforehand) track in the queue doesn't have any album art in the notification; subsequent tracks (pre-cached by Ultrasonic) display the album art just fine.
I have opus transcoding set up with .opus as the target extension.

EDIT: I've tracked it down a bit further. If no tracks from a particular album/release have been cached by Ultrasonic, everything happens as described above. However, if something else from that same album/release has been cached, album art will be displayed as normal.
Furthermore, if no tracks from %album% have been cached and no album art is displayed, you can "refresh" the latter by pausing and resuming playback after the track has been cached completely.

**Comment by sserenade** [comment]
>What kind of audio files do you use? I see the problem too with m4a files. mp3s work. The cover is shown in Now Playing but not in the notification, lock screen and widget.

My collection is largely flac. I do have some m4a and mp3 files that I've just tested with, though.

- flac: No album art shown.
- m4a: No album art shown.
- mp3: Album art is shown as normal. I don't observe the behavior described by @mradermaxlol , album art is shown in the notification for the first song as soon as it is downloaded, even if the album isn't pre-cached at all. Perhaps because no transcoding is taking place?

Currently on my Airsonic server everything except mp3 is set to transcode to mp3, with `ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -` with 320 set as the bitrate manually in Ultrasonic settings.

---

It's interesting that the one album I tested this with on the demo Navidrome server didn't work (credentials at https://www.navidrome.org/demo/), and that it also happened to be mp3. On that server, I observe the following, and I encourage others to test as well:

- [The first song on this album](https://demo.navidrome.org/app/#/album/4ed8e78631cc5682074638741374e218/show) does show art in the notification. It's ~248kbps MP3.
- [The first song on this album](https://demo.navidrome.org/app/#/album/4d2227515a538fc9650d77189ea75ec2/show) does not show album art in the notification. It's ~128kbps MP3.

Downloading these files and running `mediainfo` on them to compare reveals that the song that shows album art has it embedded in the ID3 tags. 

Would it be reasonable to conclude that Ultrasonic is using the file's metadata to create the notification, and perhaps it could somehow instead override/append the album art with the same source that the "Now Playing" view uses? Further, perhaps transcoding removes this metadata in some cases?

**Comment by mradermaxlol** [comment]
As we are digging deeper here, I think I should also note that in my case
1) all source files are flac with vorbis tags (no spec-violating flacs with ID3)
2) album art is always embedded in the tag section
3) transcoding is set up on Navidrome's side, it `ffmpeg`s flac to opus using `libopus`; opus bitrate is set to 256kbps

I think Navidrome also sends processed (compressed) coverarts for the whole album/release previews, but I doubt that those are used in the media notification.

> I don't observe the behavior described by @mradermaxlol

Could be because we are using different versions of Ultrasonic. Media3 merge seems like a huge change, maybe something notification-related is handled differently now.

**Comment by tzugen** [comment]
It currently only shows if it is embedded in the file...

**Comment by tzugen** [comment]
Please try with the PR if you can!

**Comment by sserenade** [comment]
Thank you! I have tried with the PR and strangely, it seems that there are permissions issues accessing the album art resource on my device. I've tried in the emulator as well and no art appears there either:

```
2022-07-05 15:26:12.355  2038-2138  MediaDataManager        pid-2038                             E  Unable to load bitmap
                                                                                                    java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.moire.ultrasonic.debug/files/artwork/d00b7b8a243acb8c70bd1fb0b4c4604c.jpeg: open failed: EACCES (Permission denied)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:575)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:160)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:115)
                                                                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1516)
                                                                                                    	at android.graphics.ImageDecoder$ContentResolverSource.createImageDecoder(ImageDecoder.java:278)
                                                                                                    	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1870)
                                                                                                    	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1863)
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadBitmapFromUri(MediaDataManager.kt:707)
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadBitmapFromUri(MediaDataManager.kt:669)
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:548)
                                                                                                    	at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:96)
                                                                                                    	at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:354)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:561)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:160) 
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:115) 
                                                                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1516) 
                                                                                                    	at android.graphics.ImageDecoder$ContentResolverSource.createImageDecoder(ImageDecoder.java:278) 
                                                                                                    	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1870) 
                                                                                                    	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1863) 
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadBitmapFromUri(MediaDataManager.kt:707) 
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadBitmapFromUri(MediaDataManager.kt:669) 
                                                                                                    	at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:548) 
                                                                                                    	at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:96) 
                                                                                                    	at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:354) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-07-05 15:26:12.361 27943-27943 NotificationProvider    org.moire.ultrasonic.debug           D  Failed to load bitmap
                                                                                                      java.lang.UnsupportedOperationException: Unsupported scheme: file
                                                                                                          at androidx.media3.session.SimpleBitmapLoader.load(SimpleBitmapLoader.java:94)
                                                                                                          at androidx.media3.session.SimpleBitmapLoader.lambda$loadBitmap$2(SimpleBitmapLoader.java:80)
                                                                                                          at androidx.media3.session.SimpleBitmapLoader$$ExternalSyntheticLambda1.call(Unknown Source:2)
                                                                                                          at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
                                                                                                          at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
                                                                                                          at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:920)
```

**Comment by tzugen** [comment]
You can try again :)

**Comment by sserenade** [comment]
I'm able to make the notification display album art now, but only if the artwork file is already cached before playback begins. The behavior for me is now as described in [this comment](#issuecomment-1165898573), except that pausing and playing after the track is cached will not cause the art to display.

Using the debugger, it seems that somehow, upon first play of a cached track, `metadata.artworkUri` in `MediaPlayerController` is null even when it should be set [here](https://github.com/ultrasonic/ultrasonic/blob/albumart/ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/MediaPlayerController.kt#L693=). If I quit and relaunch the app, or play another song and then play the cached song again, `artworkUri` contains a value and art is shown in the notification.

**Comment by tzugen** [comment]
OK, as least something.
Currently we can't update the Metadata of the MediaItem. It's a shortcoming of Media3. They are aware of it and want to change it, but until then I think it will be like this.

**Comment by tzugen** [comment]
I will probably merge the PR soon, please open later(!) a new Issue in Gitlab to track making this perfect.
I think we can tap into the imageloader to ensure that the artwork is even shown on first play.

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/768
